name: CI

on: [push,pull_request]

jobs:
  compile:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: 11
      - name: Install modules
        run: npm install
      - name: Compile
        uses: iCrawl/action-tsc@v1
